name = "tight-truth-243e"
main = "worker.js"
compatibility_date = "2024-04-19"

## fundamentals are no longer fetched via external APIs; no vars needed here

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
# Replace with your actual D1 database name and ID
binding = "DB"
database_name = "stock-db"
database_id = "622ab108-c7b6-4df9-a481-766b7e9a4b30"
